---
# syntax - https://github.com/redhat-plumbers-in-action/advanced-issue-labeler#policy

policy:
  - template: [bug.yml]
    section:
      - id: [component]
        #block-list: [other]
        label:
          - name: bug
            keys: ['bug']
          - name: test
            keys: ['test-option']
          - name: feature
            keys: ['feature-request']