name: Bug Report
description: A report of an error in a recent systemd version
##labels: ["triage"]

body:
  - type: markdown
    attributes:
      value: Thanks for taking the time to fill out this bug report!

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Please chose components related to this issue.
      multiple: true
      # When updating list of components please also update labeling policy
      # policy: `.github/advanced-issue-labeler.yml`
      options:
        - 'test-option'
        - 'bug'
    validations:
      required: false