name: Unresolveable Comment
run-name: ${{ github.actor }} is learning GitHub Actions
on:
  project_card:
    types: [moved]
jobs:
  unresolve-comment:
    permissions: read-all|write-all
    runs-on: ubuntu-latest
    steps:
      - name: Add Comment to issue
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
                issue_number: context.project_card.node_id,
                owner: context.repository.owner,
                repo: context.repository.repo,
                body: literal_block
              })  
    
