name: Unresolveable Issue v1
on:
  issues:
    types: [closed]
jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - env:
          EVENT_CONTEXT: ${{ toJSON(github.event) }}
        run: |
          echo $EVENT_CONTEXT
  close:
    if: github.event.issue.state_reason == 'not_planned'
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Add Comment
        uses: actions/github-script@v6
        with:
          script: |
            var msg = "Issue is closed without reason."
            github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: msg
              })