name: Unresolveable Comment v1
run-name: ${{ github.actor }} is learning GitHub Actions
on:
  project_card:
    types: [moved]
jobs:
  unresolve-comment:
    permissions: read-all|write-all
    runs-on: ubuntu-latest
    steps:
      - name: View context attributes
        uses: actions/github-script@v6
        with:
          script: console.log(context)