name: Unresolveable Comment v1
on:
  issues:
    types: [opened, edited, milestoned]
jobs:
  print_context:
    runs-on: ubuntu-latest
    steps:
      - env:
          EVENT_CONTEXT: ${{ toJSON(github.event) }}
        run: |
          echo $EVENT_CONTEXT