name: Unresolveable Comment v1
on:
  project_card:
    types: [moved, created]
jobs:
  unresolve-comment:
    permissions:
      issues: write
    runs-on: ubuntu-latest
    steps:
      - name: View context attributes
        uses: actions/github-script@v6
        with:
          script: console.log(context)