name: Unresolveable Issue v1
on:
  issues:
    types: [closed]
jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - env:
          EVENT_CONTEXT: ${{ toJSON(github.event) }}
        run: |
          echo $EVENT_CONTEXT
  close_feature:
    if: github.event.issue.state_reason == 'not_planned' && contains(github.event.issue.labels.*.name, 'feature')
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: aws-actions/closed-issue-message@v1
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          message: |
            ### ⚠️COMMENT VISIBILITY WARNING⚠️ 
            This feature has been closed temporaily or permanently.
            The reason is due to time constraints, issues with making, or other cases.
            This feature could be re-opened in the future.
  close_bug:
    if: github.event.issue.state_reason == 'not_planned' && contains(github.event.issue.labels.*.name, 'bug')
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: aws-actions/closed-issue-message@v1
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          message: |
            ### ⚠️COMMENT VISIBILITY WARNING⚠️ 
            This bug cannot be fixed at this time.