name: Project Test
on:
  projects_v2_item:
    types:
      - created
jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - env:
          EVENT_CONTEXT: ${{ toJSON(github.event) }}
        run: |
          echo $EVENT_CONTEXT